sudo: false

language: python
python:
- 3.5

cache:
  pip: true
  directories:
  - env
  - data/templates
before_cache:
- find data/templates -name "*.yml" -o "*.png" -o "*.jpg" -delete

env:
  global:
  - RANDOM_SEED=0

install:
- pip install coveralls scrutinizer-ocular

before_script:
- make env
- make depends-ci

script:
- make ci

after_success:
- coveralls
- ocular

notifications:
  email:
    on_success: never
    on_failure: change
